name: nfc_counter
description: Example project for my NFC Medium article see https://blog.devowl.de
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  nfc_manager: ^3.2.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
